#!/bin/bash
#SBATCH --job-name=dqn
#SBATCH --output=job.out
#SBATCH --exclusive
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1g
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu 
#SBATCH --array=0-7

cd /scratch/lu.xue/dec-hdrqn

srun python main.py --env_name capture_target --n_quant 16 --init_hysteretic 0.2 --end_hysteretic 0.4 --implicit 1 --likely 1 --distort_type wang --distort_param 0.0 --run_id $SLURM_ARRAY_TASK_ID