#!/bin/bash
#SBATCH --job-name=dqn
#SBATCH --output=job.out
#SBATCH --exclusive
#SBATCH --cpus-per-task=6
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1g
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu 
#SBATCH --array=0-16

cd /scratch/lu.xue/dec-hdrqn

srun python main.py --env_name capture_target --n_target 1 -x 3 -y 3 -q 16 -e 0.2 --end_hysteretic 0.4  -i 1 --likely 1 --run_id $SLURM_ARRAY_TASK_ID